name: Docker Image CI
 
on:
  pull_request:
    types: [opened, reopened]
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
          
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag icho:$(date +%s)

  go-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16
        
      - name: Build
        run: go build -v ./...
  test:
      runs-on: ubuntu_latest
      steps:
      - uses: actions/checkout@v3
      - name: setup go 
        uses: actions/setup-go@v3
        with:
          go-version: 1.16
      - name: Test
        run: go test -v ./...
      
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.SuperSecret }}
        run: |
          echo "$SUPER_SECRET"
